# Generated by Django 4.1.3 on 2023-03-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_alter_employee_active_alter_employee_department_and_more'),
        ('pto_requests', '0015_ptorequest_employee_alter_ptorequest_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptorequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='date_requested',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='ptorequest',
            name='hours_requested',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
