# Generated by Django 4.1.3 on 2022-11-06 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_nubmer', models.IntegerField()),
                ('employee_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=30)),
                ('hire_date', models.DateField()),
                ('status', models.BooleanField()),
                ('supervisor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supervisors.supervisor')),
            ],
        ),
    ]
