# Generated by Django 4.1.3 on 2023-03-13 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0022_alter_employee_active_alter_employee_department_and_more'),
        ('pto_requests', '0016_alter_ptorequest_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('pto_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pto_requests.ptorequest')),
            ],
        ),
    ]
